# Generated by Django 5.1.4 on 2025-02-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compañias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(default='Sin definir', max_length=255, unique=True, verbose_name='Razon Social')),
                ('nit', models.IntegerField(default=0, unique=True, verbose_name='Nit')),
                ('telefonoPrincipal', models.IntegerField(default=0, max_length=12, verbose_name='Telefono Principal de Empresa')),
                ('correo', models.CharField(max_length=255, null=True, verbose_name='Correo Electronico')),
                ('nombreRepresentante', models.CharField(default='Sin definir', max_length=255, verbose_name='Nombre Representante')),
                ('telefonoAsesor', models.IntegerField(unique=True, verbose_name='Telefono de Asesor')),
                ('totalCompras', models.FloatField(default=0, verbose_name='Total de Compras')),
                ('modeloFactura', models.CharField(choices=[('Calculado', 'Iva Calculado'), ('No Calculado', 'Iva No Calculado'), ('Exento', 'Iva Exento')], default='No Calculado', max_length=50, verbose_name='Modelo de Factura')),
                ('compañiaAsociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compañias.compañia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
