# Generated by Django 4.1.2 on 2022-11-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=255, unique=True, verbose_name='Razon Social')),
                ('nit', models.CharField(max_length=255, unique=True, verbose_name='Nit')),
                ('telefono', models.IntegerField(max_length=255, unique=True, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=255, unique=True, verbose_name='Correo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
            ],
        ),
    ]
