# Generated by Django 4.1.2 on 2022-11-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distribuidores',
            new_name='Distribuidor',
        ),
    ]
