# Generated by Django 5.1.4 on 2025-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='nit',
            field=models.CharField(default=0, max_length=12, unique=True, verbose_name='Nit'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='telefonoAsesor',
            field=models.CharField(max_length=12, unique=True, verbose_name='Telefono de Asesor'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='telefonoPrincipal',
            field=models.CharField(default=0, max_length=12, verbose_name='Telefono Principal de Empresa'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='totalCompras',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Total de Compras'),
        ),
    ]
