# Generated by Django 4.1.2 on 2022-11-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0002_rename_distribuidores_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='telefono',
            field=models.CharField(max_length=255, unique=True, verbose_name='Telefono'),
        ),
    ]
