# Generated by Django 5.1.4 on 2025-02-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compañias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255, unique=True, verbose_name='Dirección')),
                ('ventasTotales', models.FloatField(unique=True, verbose_name='Ventas totales de la sede')),
                ('comprasTotales', models.FloatField(unique=True, verbose_name='Compras totales de la sede')),
                ('companiaPerteneciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sede_Compañia', to='compañias.compañia')),
            ],
        ),
    ]
