# Generated by Django 5.1.4 on 2025-02-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='comprasTotales',
            field=models.FloatField(verbose_name='Compras totales de la sede'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ventasTotales',
            field=models.FloatField(verbose_name='Ventas totales de la sede'),
        ),
    ]
