# Generated by Django 5.1.4 on 2025-02-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_alter_sede_comprastotales_alter_sede_ventastotales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='comprasTotales',
            field=models.FloatField(default=0.0, verbose_name='Compras totales de la sede'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ventasTotales',
            field=models.FloatField(default=0.0, verbose_name='Ventas totales de la sede'),
        ),
    ]
