# Generated by Django 5.1.4 on 2025-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0003_alter_sede_comprastotales_alter_sede_ventastotales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='comprasTotales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Compras totales de la sede'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ventasTotales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Ventas totales de la sede'),
        ),
    ]
