# Generated by Django 5.1.4 on 2025-02-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociosMinoristas', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ganancia',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociosMinoristas.sociominorista'),
        ),
    ]
