# Generated by Django 4.1.2 on 2022-11-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_detventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
