# Generated by Django 5.1.4 on 2025-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_ganancia_alter_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estadoVenta',
            field=models.CharField(choices=[('PAGO', 'Pago'), ('PENDIENTE', 'Pendiente'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Venta'),
        ),
    ]
