# Generated by Django 5.1.4 on 2025-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_estadoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estadoVenta',
            field=models.CharField(choices=[('PAGO', 'Pago'), ('PENDIENTE', 'Pendiente'), ('DEVUELTO', 'Devuelto')], default='PAGO', max_length=10, verbose_name='Estado de la Venta Actual'),
        ),
    ]
