# Generated by Django 4.1.2 on 2022-12-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='detventa',
            name='precio',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
    ]
