# Generated by Django 5.1.4 on 2025-02-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('distribuidores', '0001_initial'),
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Referencia')),
                ('precioCosto', models.FloatField(verbose_name='Precio Distribuidor')),
                ('tasaGanacia', models.FloatField(verbose_name='Porcentaje de Ganancia')),
                ('iva', models.FloatField(verbose_name='Iva (calculado antes de ganancia)')),
                ('precioFinal', models.FloatField(verbose_name='Precio Publico')),
                ('stock', models.IntegerField(verbose_name='Cantidad Unidades')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria', verbose_name='Categoria')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidores.distribuidor')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marcas.marca', verbose_name='Marca')),
            ],
        ),
    ]
