# Generated by Django 5.1.4 on 2025-02-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('sedes', '0003_alter_sede_comprastotales_alter_sede_ventastotales'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sedes.sede'),
            preserve_default=False,
        ),
    ]
