# Generated by Django 4.1.2 on 2022-11-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto/%y/%m/%d'),
        ),
    ]
