# Generated by Django 4.1.2 on 2022-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precioFinal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
