# Generated by Django 5.1.4 on 2025-02-18 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_articulo_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Guardado')),
                ('precio_iva_incluido', models.CharField(max_length=255, verbose_name='Precio de Compra Iva Incluido')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
            ],
        ),
    ]
