# Generated by Django 5.1.4 on 2025-02-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_historico_precios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico_precios',
            name='precio_iva_incluido',
        ),
        migrations.AddField(
            model_name='historico_precios',
            name='precioIvaIncluido',
            field=models.CharField(default=0, max_length=255, verbose_name='Precio de Compra Iva Incluido'),
            preserve_default=False,
        ),
    ]
