# Generated by Django 5.1.4 on 2025-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_remove_historico_precios_precio_iva_incluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descuentoAntesDeIva',
            field=models.FloatField(default=0, verbose_name='Descuento Por Distribuidor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioCosto',
            field=models.FloatField(verbose_name='Precio Distribuidor (antes de IVA)'),
        ),
    ]
