# Generated by Django 4.1.2 on 2022-11-24 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_descripcion_alter_categoria_nombre'),
        ('marcas', '0001_initial'),
        ('articulos', '0004_remove_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='detalle',
            field=models.CharField(max_length=255, verbose_name='Descripcion detallada'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marcas.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioCosto',
            field=models.FloatField(verbose_name='Precio Distribuidor'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioFinal',
            field=models.FloatField(verbose_name='Precio Publico'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(verbose_name='Cantidad Unidades'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tasaGanacia',
            field=models.FloatField(verbose_name='Porcentaje de Ganancia'),
        ),
    ]
