# Generated by Django 4.1.2 on 2022-12-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_alter_articulo_categoria_alter_articulo_detalle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='detalle',
        ),
        migrations.AddField(
            model_name='articulo',
            name='iva',
            field=models.FloatField(default=0, verbose_name='Iva calculado'),
            preserve_default=False,
        ),
    ]
