# Generated by Django 5.1.4 on 2025-02-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_articulo_descuentoantesdeiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descuentoAntesDeIva',
            field=models.FloatField(default=0.0, verbose_name='Descuento Por Distribuidor'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioCosto',
            field=models.FloatField(verbose_name='Precio Distribuidor'),
        ),
        migrations.AlterField(
            model_name='historico_precios',
            name='precioIvaIncluido',
            field=models.FloatField(max_length=255, verbose_name='Precio de Compra Iva Incluido'),
        ),
    ]
