# Generated by Django 4.1.2 on 2022-12-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_remove_articulo_detalle_articulo_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='iva',
            field=models.FloatField(verbose_name='Iva (calculado antes de ganancia)'),
        ),
    ]
