# Generated by Django 5.1.4 on 2025-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_alter_articulo_descuentoantesdeiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descuentoAntesDeIva',
            field=models.IntegerField(default=0, verbose_name='Descuento Por Distribuidor'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='iva',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Iva (calculado antes de ganancia)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioCosto',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio Distribuidor'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioFinal',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio Publico'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tasaGanacia',
            field=models.IntegerField(verbose_name='Porcentaje de Ganancia'),
        ),
        migrations.AlterField(
            model_name='historico_precios',
            name='precioIvaIncluido',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio de Compra Iva Incluido'),
        ),
    ]
