# Generated by Django 5.1.4 on 2025-03-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_articulo_descuentoantesdeiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigoOriginal',
            field=models.CharField(default=1, max_length=255, verbose_name='Referencia'),
            preserve_default=False,
        ),
    ]
