# Generated by Django 5.1.4 on 2025-03-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_articulo_codigooriginal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=255, null=True, verbose_name='Referencia'),
        ),
    ]
