# Generated by Django 5.2.5 on 2025-08-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_alter_articulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigoOriginal',
            field=models.CharField(max_length=255, verbose_name='Codigo Original'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioFinal',
            field=models.IntegerField(verbose_name='Precio Publico'),
        ),
    ]
