# Generated by Django 5.2.5 on 2025-08-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_alter_articulo_codigooriginal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precioFinal',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio Publico'),
        ),
    ]
