# Generated by Django 5.1.4 on 2025-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compañia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(default='Sin definir', max_length=255, unique=True, verbose_name='Razon Social')),
                ('nit', models.IntegerField(default=0, unique=True, verbose_name='Nit')),
                ('telefonoPrincipal', models.IntegerField(default=0, max_length=12, verbose_name='Telefono Principal de Empresa')),
                ('correo', models.CharField(max_length=255, null=True, verbose_name='Correo Electronico')),
                ('nombreRepresentante', models.CharField(default='Sin definir', max_length=255, verbose_name='Nombre Representante')),
                ('ventasTotales', models.FloatField(unique=True, verbose_name='Ventas totales de la compañia')),
                ('comprasTotales', models.FloatField(unique=True, verbose_name='Compras totales de la compañia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
