# Generated by Django 5.1.4 on 2025-02-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compañias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compañia',
            name='comprasTotales',
            field=models.FloatField(verbose_name='Compras totales de la compañia'),
        ),
        migrations.AlterField(
            model_name='compañia',
            name='ventasTotales',
            field=models.FloatField(verbose_name='Ventas totales de la compañia'),
        ),
    ]
