# Generated by Django 5.1.4 on 2025-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compañias', '0002_alter_compañia_comprastotales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compañia',
            name='comprasTotales',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Compras totales de la compañia'),
        ),
        migrations.AlterField(
            model_name='compañia',
            name='nit',
            field=models.CharField(default=0, max_length=12, unique=True, verbose_name='Nit'),
        ),
        migrations.AlterField(
            model_name='compañia',
            name='telefonoPrincipal',
            field=models.CharField(default=0, max_length=12, verbose_name='Telefono Principal de Empresa'),
        ),
        migrations.AlterField(
            model_name='compañia',
            name='ventasTotales',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Ventas totales de la compañia'),
        ),
    ]
