# Generated by Django 5.1.4 on 2025-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Categoria')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
    ]
