# Generated by Django 5.1.4 on 2025-02-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('compañias', '0002_alter_compañia_comprastotales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='compañiaAsociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compañias.compañia'),
        ),
    ]
