# Generated by Django 5.1.4 on 2025-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compañias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioMinorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(default='Sin definir', max_length=255, unique=True, verbose_name='Razon Social')),
                ('nit', models.IntegerField(default=0, unique=True, verbose_name='Nit')),
                ('telefonoPrincipal', models.IntegerField(default=0, max_length=12, verbose_name='Telefono Principal de Empresa')),
                ('correo', models.CharField(max_length=255, null=True, verbose_name='Correo Electronico')),
                ('nombreRepresentante', models.CharField(default='Sin definir', max_length=255, verbose_name='Nombre Representante')),
                ('montoPendiente', models.FloatField(default=0, verbose_name='Dinero Pendiente')),
                ('totalVentas', models.FloatField(default=0, verbose_name='Total de Ventas Realizadas')),
                ('porcentajeDescuento', models.IntegerField(default=10, verbose_name='Descuento Fijo en Ventas')),
                ('compañiasAsociadas', models.ManyToManyField(blank=True, related_name='socios_minoristas', to='compañias.compañia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
