# Generated by Django 5.1.4 on 2025-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociosMinoristas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociominorista',
            name='montoMaximoPendiente',
            field=models.FloatField(default=200000, verbose_name='Dinero Pendiente'),
        ),
        migrations.AddField(
            model_name='sociominorista',
            name='prestamo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=10, verbose_name='Estado del Préstamo'),
        ),
    ]
