# Generated by Django 5.1.4 on 2025-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociosMinoristas', '0002_sociominorista_montomaximopendiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociominorista',
            name='montoMaximoPendiente',
            field=models.FloatField(default=0, verbose_name='Cupo maximo de prestamo'),
        ),
    ]
