# Generated by Django 5.1.4 on 2025-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociosMinoristas', '0003_alter_sociominorista_montomaximopendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociominorista',
            name='montoMaximoPendiente',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Cupo maximo de prestamo'),
        ),
        migrations.AlterField(
            model_name='sociominorista',
            name='montoPendiente',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Dinero Pendiente'),
        ),
        migrations.AlterField(
            model_name='sociominorista',
            name='nit',
            field=models.CharField(default=0, max_length=12, unique=True, verbose_name='Nit'),
        ),
        migrations.AlterField(
            model_name='sociominorista',
            name='telefonoPrincipal',
            field=models.CharField(default=0, max_length=12, verbose_name='Telefono Principal de Empresa'),
        ),
        migrations.AlterField(
            model_name='sociominorista',
            name='totalVentas',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total de Ventas Realizadas'),
        ),
    ]
