# Generated by Django 5.1.4 on 2025-02-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_companiaasociada_user_token_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companiaAsociada',
        ),
    ]
