# Generated by Django 5.1.4 on 2025-02-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compañias', '0002_alter_compañia_comprastotales_and_more'),
        ('user', '0003_remove_user_companiaasociada'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companiaAsociada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_Compañia', to='compañias.compañia'),
            preserve_default=False,
        ),
    ]
