# Generated by Django 5.1.4 on 2025-02-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_companiaasociada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companiaAsociada',
        ),
    ]
