# Generated by Django 5.1.4 on 2025-02-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_alter_sede_comprastotales_alter_sede_ventastotales'),
        ('user', '0005_remove_user_companiaasociada'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sedePerteneciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_Compañia', to='sedes.sede'),
            preserve_default=False,
        ),
    ]
