# Generated by Django 5.1.4 on 2025-02-20 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_sedeperteneciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricosComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Guardado')),
                ('comisionAcumulada', models.CharField(max_length=255, verbose_name='Valor de comisión acumulada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
