# Generated by Django 5.1.4 on 2025-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_historicoscomisiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='porcentajeComision',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
    ]
