# Generated by Django 5.1.4 on 2025-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_porcentajecomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoscomisiones',
            name='comisionAcumulada',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
    ]
