# Generated by Django 5.1.4 on 2025-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_historicoscomisiones_comisionacumulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoscomisiones',
            name='comisionAcumulada',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Comision Acumulada en el Mes'),
        ),
    ]
