# Generated by Django 5.1.4 on 2025-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detcompra',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detcompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
