# Generated by Django 4.1.2 on 2022-11-30 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0003_alter_distribuidor_telefono'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='use',
        ),
        migrations.AddField(
            model_name='compra',
            name='distribuidor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='distribuidores.distribuidor'),
            preserve_default=False,
        ),
    ]
